name: Run Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Git Checkout
      - uses: actions/checkout@v2
      - name: Setup Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: "lts"
      - name: Install Dependencies
        run: yarn
      - name: Run Unit Tests
        run: yarn test